# Generated by Django 5.2.14 on 2026-05-07 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado actual de la reserva', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(help_text='Fecha de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(help_text='Hora de fin de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(help_text='Hora de inicio de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='laboratorio',
            field=models.CharField(help_text='Nombre del laboratorio a reservar', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='motivo',
            field=models.TextField(help_text='Motivo o descripción detallada de la reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que realiza la reserva', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
